# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WeCare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift'
  pod 'CocoaLumberjack/Swift'
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'SwiftLint'
  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
  pod 'SideMenu'
  pod 'R.swift'
end
